// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class Fornecedores
{
    public int Focodigo { get; set; }

    public string Fonome { get; set; }

    public string Focnpj { get; set; }

    public string FoinscricaoEstadual { get; set; }

    public string FoinscricaoMunicipal { get; set; }

    public string Foemail { get; set; }

    public virtual ICollection<Endereco> Endereco { get; set; } = new List<Endereco>();

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual ICollection<Servicos> Servicos { get; set; } = new List<Servicos>();

    public virtual ICollection<Solicitacao> Solicitacao { get; set; } = new List<Solicitacao>();
}