// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class OrdemCompra
{
    public int Occodigo { get; set; }

    public int? OccodFornecedor { get; set; }

    public DateTime? Ocdata { get; set; }

    public bool? Ocsolicitada { get; set; }

    public virtual ICollection<OrdemCompraSolicitacao> OrdemCompraSolicitacao { get; set; } = new List<OrdemCompraSolicitacao>();
}