// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class Produtos
{
    public long PrcodigoEan { get; set; }

    public string Prdescricao { get; set; }

    public decimal? PrprecoUnitario { get; set; }

    public int? PrcotaMinimaEstoque { get; set; }

    public int? PrcodUnidade { get; set; }

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual Unidade PrcodUnidadeNavigation { get; set; }

    public virtual ICollection<Saida> Saida { get; set; } = new List<Saida>();

    public virtual ICollection<Solicitacao> Solicitacao { get; set; } = new List<Solicitacao>();
}