// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class Saida
{
    public int Sacodigo { get; set; }

    public int? SacodUsuario { get; set; }

    public long? SacodProduto { get; set; }

    public int? SacodDepartamento { get; set; }

    public DateTime? Sadata { get; set; }

    public int? Saquantidade { get; set; }
}