// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class Servicos
{
    public int Secodigo { get; set; }

    public string Senome { get; set; }

    public string Sedescricao { get; set; }

    public int? SecodFornecedor { get; set; }

    public DateTime? SeprazoEntrega { get; set; }

    public virtual Fornecedores SecodFornecedorNavigation { get; set; }

    public virtual ICollection<Solicitacao> Solicitacao { get; set; } = new List<Solicitacao>();
}