// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class Solicitacao
{
    public int Socodigo { get; set; }

    public long? SocodProduto { get; set; }

    public int? Soquantidade { get; set; }

    public int? SocodDepartamento { get; set; }

    public int? SocodUsuario { get; set; }

    public DateTime? Sodata { get; set; }

    public int? SocodServico { get; set; }

    public int? SocodFornecedor { get; set; }

    public string Soobservacao { get; set; }

    public bool? Soconcluida { get; set; }

    public virtual ICollection<OrdemCompraSolicitacao> OrdemCompraSolicitacao { get; set; } = new List<OrdemCompraSolicitacao>();

    public virtual Departamento SocodDepartamentoNavigation { get; set; }

    public virtual Fornecedores SocodFornecedorNavigation { get; set; }

    public virtual Produtos SocodProdutoNavigation { get; set; }

    public virtual Servicos SocodServicoNavigation { get; set; }

    public virtual Usuarios SocodUsuarioNavigation { get; set; }
}