// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class Unidade
{
    public int Uncodigo { get; set; }

    public string Undescricao { get; set; }

    public virtual ICollection<Produtos> Produtos { get; set; } = new List<Produtos>();
}