// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class Usuarios
{
    public int Usmatricula { get; set; }

    public string Usnome { get; set; }

    public int? UscodDepartamento { get; set; }

    public virtual ICollection<Solicitacao> Solicitacao { get; set; } = new List<Solicitacao>();

    public virtual Departamento UscodDepartamentoNavigation { get; set; }
}