// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Teste_Aptidao_UGB.Model.Models;

public partial class VwEstoque
{
    public int? Quantidade { get; set; }

    public long? EtcodProduto { get; set; }

    public string Prdescricao { get; set; }
}